/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "bakery.h"
#include <pthread.h>
#include <stdlib.h>
#include <unistd.h>

int flag = 1;
void sig_handler(int sig_num)
{
	flag = 0;
}
void bakery_prog_1(char *host)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	void *result_1;
	int register_proc_1_arg;
	enum clnt_stat retval_2;
	int result_2;
	int get_number_proc_1_arg;
	enum clnt_stat retval_3;
	long result_3;
	int result_proc_1_arg;
	int ready = 0;

	clnt = clnt_create(host, BAKERY_PROG, BAKERY_VER, "udp");
	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(1);
	}

	while (flag)
	{
		register_proc_1_arg = getpid() % MAX_CLIENTS;
		retval_1 = register_proc_1(&register_proc_1_arg, &result_1, clnt);
		if (retval_1 != RPC_SUCCESS)
		{
			clnt_perror(clnt, "call failed");
		}
		get_number_proc_1_arg = getpid() % MAX_CLIENTS;

		ready = 0;
		while (!ready)
		{
			retval_2 = get_number_proc_1(&get_number_proc_1_arg, &result_2, clnt);
			if (retval_2 != RPC_SUCCESS)
			{
				clnt_perror(clnt, "call failed");
			}
			else if (result_2 != -1)
			{
				ready = 1;
			}
		}

		result_proc_1_arg = getpid() % MAX_CLIENTS;
		retval_3 = result_proc_1(&result_proc_1_arg, &result_3, clnt);
		if (retval_3 != RPC_SUCCESS)
		{
			clnt_perror(clnt, "call failed");
		}

		printf("%d, %ld\n", result_2, result_3);
	}

	clnt_destroy(clnt);
}

int main(int argc, char *argv[])
{
	char *host;

	if (argc < 2)
	{
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	if (signal(SIGINT, sig_handler) == SIG_ERR)
	{
		perror("signal");
		exit(1);
	}
	host = argv[1];
	bakery_prog_1(host);
	exit(0);
}
