/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "bakery.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = {25, 0};

enum clnt_stat
register_proc_1(int *argp, void *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, REGISTER_PROC,
					  (xdrproc_t)xdr_int, (caddr_t)argp,
					  (xdrproc_t)xdr_void, (caddr_t)clnt_res,
					  TIMEOUT));
}

enum clnt_stat
get_number_proc_1(int *argp, int *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, GET_NUMBER_PROC,
					  (xdrproc_t)xdr_int, (caddr_t)argp,
					  (xdrproc_t)xdr_int, (caddr_t)clnt_res,
					  TIMEOUT));
}

enum clnt_stat
result_proc_1(int *argp, long *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, RESULT_PROC,
					  (xdrproc_t)xdr_int, (caddr_t)argp,
					  (xdrproc_t)xdr_long, (caddr_t)clnt_res,
					  TIMEOUT));
}
