/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _BAKERY_H_RPCGEN
#define _BAKERY_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>
#define MAX_CLIENTS 5000

#ifdef __cplusplus
extern "C"
{
#endif

#define BAKERY_PROG 0x20000001
#define BAKERY_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define REGISTER_PROC 1
    extern enum clnt_stat register_proc_1(int *, void *, CLIENT *);
    extern bool_t register_proc_1_svc(int *, void *, struct svc_req *);
#define GET_NUMBER_PROC 2
    extern enum clnt_stat get_number_proc_1(int *, int *, CLIENT *);
    extern bool_t get_number_proc_1_svc(int *, int *, struct svc_req *);
#define RESULT_PROC 3
    extern enum clnt_stat result_proc_1(int *, long *, CLIENT *);
    extern bool_t result_proc_1_svc(int *, long *, struct svc_req *);
    extern int bakery_prog_1_freeresult(SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define REGISTER_PROC 1
extern enum clnt_stat register_proc_1();
extern bool_t register_proc_1_svc();
#define GET_NUMBER_PROC 2
extern enum clnt_stat get_number_proc_1();
extern bool_t get_number_proc_1_svc();
#define RESULT_PROC 3
extern enum clnt_stat result_proc_1();
extern bool_t result_proc_1_svc();
extern int bakery_prog_1_freeresult();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_BAKERY_H_RPCGEN */
