/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "bakery.h"
#include <stdio.h>
#include <unistd.h>
#include <time.h>
#include <pthread.h>
#include <math.h>

int numbers[MAX_CLIENTS];
int results[MAX_CLIENTS] = {-1};
int max_number = 0;
pthread_mutex_t mutex = PTHREAD_MUTEX_INITIALIZER;

void *find_max_number(void *arg)
{
	int idx = *((int *)arg);
	pthread_mutex_lock(&mutex);
	for (int i = 0; i < MAX_CLIENTS; ++i)
		if (numbers[i] > max_number)
			max_number = numbers[i];
	max_number++;
	numbers[idx] = max_number;
	results[idx] = max_number;
	pthread_mutex_unlock(&mutex);

	free(arg);
	pthread_exit(NULL);
}

bool_t
register_proc_1_svc(int *argp, void *result, struct svc_req *rqstp)
{
	bool_t retval;
	pthread_t tid;
	int *arg = malloc(sizeof(int));
	if (!arg)
		return FALSE;

	*arg = *argp;
	if (pthread_create(&tid, NULL, find_max_number, arg) != 0)
	{
		free(arg);
		return FALSE;
	}
	pthread_detach(tid);

	return TRUE;
}

bool_t
get_number_proc_1_svc(int *argp, int *result, struct svc_req *rqstp)
{
	int id = *argp;
	if (results[id] == -1)
	{
		*result = -1;
	}
	else
	{
		*result = results[id];
		results[id] = -1;
	}

	return TRUE;
}

bool_t
result_proc_1_svc(int *argp, long *result, struct svc_req *rqstp)
{
	int j = *argp;
	struct timespec end;

	int ticket = numbers[j];
	for (int i = 0; i < MAX_CLIENTS; ++i)
	{
		while ((numbers[i] != 0) && ((numbers[i] < numbers[j]) || (numbers[i] == numbers[j]) && (i < j)))
			;
	}

	clock_gettime(CLOCK_MONOTONIC, &end);
	*result = end.tv_nsec;
	numbers[j] = 0;

	return TRUE;
}

int bakery_prog_1_freeresult(SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free(xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}
