/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "calculator.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
calculator_proc_1(struct CALCULATOR *argp, struct CALCULATOR *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, CALCULATOR_PROC,
		(xdrproc_t) xdr_CALCULATOR, (caddr_t) argp,
		(xdrproc_t) xdr_CALCULATOR, (caddr_t) clnt_res,
		TIMEOUT));
}
