/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _BAKERY_H_RPCGEN
#define _BAKERY_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define BAKERY_PROG 0x30000001
#define BAKERY_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define GET_TICKET_NUMBER 1
extern  int * get_number_1(int *, CLIENT *);
extern  int * get_number_1_svc(int *, struct svc_req *);
#define GET_SERVICE_TIME 2
extern  quad_t * get_service_time_1(int *, CLIENT *);
extern  quad_t * get_service_time_1_svc(int *, struct svc_req *);
extern int bakery_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GET_TICKET_NUMBER 1
extern  int * get_number_1();
extern  int * get_number_1_svc();
#define GET_SERVICE_TIME 2
extern  quad_t * get_service_time_1();
extern  quad_t * get_service_time_1_svc();
extern int bakery_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_BAKERY_H_RPCGEN */
