/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "bakery.h"

#include <stdlib.h>
#include <stdio.h>
#include <signal.h>
#include <errno.h>
#include <sys/types.h>
#include <unistd.h>

int flag = 1;
void sig_handler(int sig_num)
{
	flag = 0;
	printf("PID: %d\n", getpid());
}

void
bakery_prog_1(char *host)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	int result_1;
	char *get_number_1_arg;
	enum clnt_stat retval_2;
	struct BAKERY_RESULT result_2;
	int  bakery_proc_1_arg;

	char buff[100];

#ifndef	DEBUG
	clnt = clnt_create (host, BAKERY_PROG, BAKERY_VER, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	//printf("NUMBER");
	retval_1 = get_number_1((void*)&get_number_1_arg, &result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	//printf("AFTER NUMBER");
	bakery_proc_1_arg = result_1;
	result_2.is_recieved_time = 0;
	srand((unsigned int)time(NULL));

	while (result_2.is_recieved_time == 0)//&&flag
	{
		//printf("REQUEST");
		retval_2 = bakery_proc_1(&bakery_proc_1_arg, &result_2, clnt);
		if (retval_2 != RPC_SUCCESS) {
			clnt_perror (clnt, "call failed");
			exit(1);
		}
		if (result_2.is_recieved_time)
		{
			printf("%ld %d\n", result_2.time, bakery_proc_1_arg);
		}
		else
		{
			printf("%d\n is waiting", bakery_proc_1_arg);
		}
		}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	if (signal(SIGINT, sig_handler) == SIG_ERR)
	{
		perror("signal");
		printf("errno: %d\n", errno);
		exit(1);
	}
	srand(getpid());
	while(flag)
	{
		bakery_prog_1 (host);
	}
exit (0);
}
