/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "bakery.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
get_number_1(void *argp, int *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, GET_NUMBER,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
bakery_proc_1(int *argp, struct BAKERY_RESULT *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, BAKERY_PROC,
		(xdrproc_t) xdr_int, (caddr_t) argp,
		(xdrproc_t) xdr_BAKERY_RESULT, (caddr_t) clnt_res,
		TIMEOUT));
}
