/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _BAKERY_H_RPCGEN
#define _BAKERY_H_RPCGEN

#include <time.h>
#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif

#define CLIENT_COUNT 6

struct BAKERY_RESULT {
	long time;
	int is_recieved_time;
};
typedef struct BAKERY_RESULT BAKERY_RESULT;

#define BAKERY_PROG 0x20000001
#define BAKERY_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define GET_NUMBER 1
extern  enum clnt_stat get_number_1(void *, int *, CLIENT *);
extern  bool_t get_number_1_svc(void *, int *, struct svc_req *);
#define BAKERY_PROC 2
extern  enum clnt_stat bakery_proc_1(int *, struct BAKERY_RESULT *, CLIENT *);
extern  bool_t bakery_proc_1_svc(int *, struct BAKERY_RESULT *, struct svc_req *);
extern int bakery_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GET_NUMBER 1
extern  enum clnt_stat get_number_1();
extern  bool_t get_number_1_svc();
#define BAKERY_PROC 2
extern  enum clnt_stat bakery_proc_1();
extern  bool_t bakery_proc_1_svc();
extern int bakery_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_BAKERY_RESULT (XDR *, BAKERY_RESULT*);

#else /* K&R C */
extern bool_t xdr_BAKERY_RESULT ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_BAKERY_H_RPCGEN */
