/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "bakery.h"

bool_t
xdr_BAKERY_RESULT (XDR *xdrs, BAKERY_RESULT *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->is_recieved_time))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->time))
		 return FALSE;
	return TRUE;
}
