/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculator.h"

bool_t
calculator_proc_1_svc(struct CALCULATOR *argp, struct CALCULATOR *result, struct svc_req *rqstp)
{
	bool_t retval = TRUE;

	switch(argp->op)
	{
		case ADD:
			result->result = argp->arg1 + argp->arg2;
			break;
		case SUB:
			result->result = argp->arg1 - argp->arg2;
			break;
		case MUL:
			result->result = argp->arg1 * argp->arg2;
			break;
		case DIV:
			result->result = argp->arg1 / argp->arg2;
			break;
		default:
			retval = FALSE;
			break;
	}

	return retval;
}

int
calculator_prog_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}
