/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "bakery.h"

int client_number_service = 0;
int client_num = 0;

bool_t
get_number_1_svc(void *argp, int *result, struct svc_req *rqstp)
{
	bool_t retval = TRUE;
	int max = 0;
	*result = client_num;
	client_num++;
	return retval;
}

bool_t
bakery_proc_1_svc(int *argp, struct BAKERY_RESULT *result, struct svc_req *rqstp)
{
	bool_t retval = TRUE;
	struct timespec time;

	int client_number = *argp;
	result->is_recieved_time = 0;
	if (client_number != client_number_service)
		return retval;
	result->is_recieved_time = 1;
	if (clock_gettime(CLOCK_REALTIME, &time) != 0)
		retval = FALSE;
	else
		result->time = time.tv_nsec;
	client_number_service++;

	return retval;
}

int
bakery_prog_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);
	return 1;
}
